appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: HpxKB/TPy6VuvnZLKZqUICkeOGoXCF9Kp7euA/+JlgtPqxekREyZcv/7aaA89FRDNUlGMyVbGqQxO3XmNTosPQ5wSZDZFs3ihn4ANreUne2R3EsCPflYDxjjiwwvKS9Q5wEy79JUI7OmajC53VcyYvUAg38yBbpz6voaqk/JzEGAwC69Vzp16TWWS6uNdMdP7P5lwWyAhAouu2AFuUd5L6odnxK5ZvVo2x5l96bHVyu7ojw4EIAEWZmam775jlbHBBIjyl+zHyQjPX/6vAq6k1RodRBfBSc3imbzo8kQtx8UUS3dLqBYFvIQMQuJEazMikZpbxLPxDHZlg86bqqxvV+hdn/OncMUnZvz1fI2BRYXqHNDryKmIo+6prCgukNmEb9DoAvZfpMiebRDp4nTNQXdNjZknOxjAocIMsH1ZLma2zouJR7zTmpq5BsgXR/FoN1y+5akK0GBDwzrtvUjvA9UZLSZXC1sYawqjed775V8DZU4F/MseQ+9kxzr27xWFpTv6fYUpThM+8asD/bRzbdmh5/9pRUKtwAu+MdKA4jUFMpd374ZmV5NIpjFQ0K8wbKmTQLZZEh0PbOp43UG16MStBA+Jl1vKJuPvQMga51JzXr/B0BgemWC3Pl/l12NG3jzT1icjcMLna0mVdCw29BkWkrZyVoLzauYRBj7Phg=
